name: Tarea 7
on:
    push:
        branches:
          - test_1
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Impresiones
          run: echo 
               "Impresion 1",
               "Impresion 2",
               "Impresion 3"        