name: Tarea 7
on:
    push:
        branches:
          - test_1
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Impresiones
          run: echo "Impresion 1",
               echo "Impresion 2",
               echo "Impresion 3"        